apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamAccess.fullname" . }}
  labels:
    {{- include "streamAccess.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "streamAccess.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "streamAccess.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "streamAccess.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP


          env:
            - name: "SRS_SERVER_URL"
              value: "http://srs-service:1985/api/v1"
            - name: "MYSQL_HOST"
              value : {{.Values.mysqlhost}}
            - name: "MYSQL_DB"
              value: {{.Values.mysqldb}}
            - name: "MYSQL_PORT"
              value: {{.Values.mysqlport}}
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  key: mysqlusername
                  name: {{ .Release.Name }}-auth
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: mysqlpassword
                  name: {{ .Release.Name }}-auth
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
